# -*- coding: utf-8 -*-
"""Wrold-happiness

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143A821dv55EY-yoEeQMWWdutz1irn2_9
"""

import pandas as pd
import numpy as np

df = pd.read_csv('world-happiness-report-2021.csv')

df.drop(df.columns[[0,1,3,4,5,12,13,14,15,16,17,18,19]],axis=1, inplace =True)

X = df.iloc[:, 1:].values
y = df.iloc[:, 1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(random_state = 0)
regressor.fit(X_train, y_train)


print("Accuracy on training set: {:.3f}".format(regressor.score(X_train, y_train)))
print("Accuracy on test set: {:.3f}".format(regressor.score(X_test, y_test)))